#!/usr/bin/env bash
# Xfer file to web-01 server
# 4 parameters: file, host, user, password

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$2":"$3"
fi
