#!/usr/bin/env bash
#  Install nginx on web-01 server

sudo apt -y update && sudo apt -y upgrade
sudo apt -y install nginx
sudo /etc/init.d/nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart
