#!/usr/bin/env bash
#  Install nginx on web-01 server

sudo apt -y update && sudo apt -y upgrade
sudo apt -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"
sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
