#!/usr/bin/env bash
#  Install nginx on web-01 server

sudo apt -y update && sudo apt -y upgrade
sudo apt -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
search="^\tlocation / {"
alt="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sed -i "s/$search/$alt/g" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
