#!/usr/bin/env bash
#  Install nginx on web-01 server

sudo apt -y update && sudo apt -y upgrade
sudo apt -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo /etc/init.d/nginx start
link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"
location_error="location = /404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n"
error_directive="error_page 404 /404.html;\n\t$location_error"
error_404="}\n\n\t$error_directive\t}"
sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
sed -i "0,/}/ s|}|$error_404|" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
