#!/usr/bin/env bash
#Creates the file /var/run/holbertonscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
FILE=/var/run/holbertonscript.pid
echo "($$)" > $FILE
trap 'echo "I hate the kill command"' SIGTERM
trap "{ echo 'Y U no love me?!'; }" SIGINT
trap 'rm -f "$FILE"' SIGQUIT SIGTERM
i=1
while (( i <= 100 ))
do
    echo "To infinity and beyond"
    (( i+i ))
    sleep 5
done
