#!/usr/bin/env bash
#Creates the file /var/run/holbertonscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

#trap "echo I hate the kill command" SIGTERM
#trap "rm -f $FILE" SIGTERM
#trap "rm -f $FILE" SIGQUIT 
trap "echo Y U no love me?!" SIGINT
#kill -- -$$ # Sends SIGTERM to child/sub processes

function cleanup {
       	echo "I hate the kill command"
	rm $FILE
	exit $?
}



#FILE=/var/run/holbertonscript.pid
FILE=./holbertonscript.pid
echo "$$" > $FILE
while :
do
    echo "To infinity and beyond $$"
    a=1
    sleep 5
    trap cleanup SIGQUIT
    trap cleanup SIGTERM
done


