#!/usr/bin/env bash
# Write a manage_my_process Bash script that:



PFILE=./my_process.pid

case "$1" in
   # start) start ;;
   # stop) stop;;
   # restart) restart;;
    
    
    
    start)
        echo $$ > $PFILE; ./manage_my_process
        echo -n "manage_my_process started"
        ;;


    stop)
        pkill -f 101-manage_my_process
        rm -f "$PFILE"
        echo -n "manage_my_process stopped"
        ;;


    restart)
        $0 stop
        $0 start
        #pkill -f 101-manage_my_process
        #rm -f "/var/run/myprocess.pid"
        #sh -c echo $$ > $FILE; .manage_my_process
        #echo -n "manage_my_process restarted"
        ;;


*) echo -n "usage $0 start|stop|restart" >&2
        exit 1
        ;;


esac
