#!/usr/bin/env bash
# Prints supersticious number arount the world
i=1
while [ $i -le 20 ]
do
    case "$i" in
        4)
        echo -e "$i\nbad luck from china" ;;
        9)
        echo -e "$i\nbad luck from japan" ;;
        17)
        echo -e "$i\nbad luck from Itally" ;;
        *) echo "$i" ;;
    esac
    (( i=i+1 ));
done
