#!/usr/bin/env bash
# Bash script that configures haproxy

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy=2.4.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 3579-web-01 54.83.188.32 check
    server 3579-web-02 54.90.147.167 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

